INSERT INTO tb_member (name, since, motorcycle, rank, sponsor, image_Uri, status) VALUES ('André Lorena', 1998, 'Fat Boy', 'Presidente', 'Fundador', 'https://i.ibb.co/NZmkqfr/Andre.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Andrezão', 2005, 'Shadow', '?', 'https://i.ibb.co/nwx6FD1/Andrez-o.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Berto', 2014, 'Dyna', 'André', 'https://i.ibb.co/pzWMGtv/Bertoloti.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, status) VALUES ('Bia', 2012, 'Fazer 250', 'Gallo', 1);
INSERT INTO tb_member (name, since, motorcycle, rank, sponsor, image_Uri, status) VALUES ('Guerra', 2010, 'Fazer', 'Diretor Eventos', 'Gallo', 'https://i.ibb.co/7j2VRSK/Guerra.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, rank, sponsor, image_Uri, status) VALUES ('Dennis', 2013, 'Shadow', 'Diretor Adjunto Evento', 'André', 'https://i.ibb.co/WHSQDnL/Denis.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, rank, sponsor, image_Uri, status) VALUES ('Di', 2008, 'Fat Boy', 'Diretor Social', 'Mineiro', 'https://i.ibb.co/42m6jSk/Di.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Diego', 2017, 'Falcon', 'Bruno', 'https://i.ibb.co/x8WfJx4/Diego.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, status) VALUES ('Du', 2004, 'FAT BOY', 'Ursão', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Fabiano', 2018, 'Twister', 'Foguinho', 'https://i.ibb.co/Q93hNkn/Fabiano.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, status) VALUES ('Faísca', 2019, 'CBR250', 'Foguinho', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, status) VALUES ('Feio', 2013, 'Midnight', 'Ferreira', 1);
INSERT INTO tb_member (name, since, sponsor, status) VALUES ('Fernanda', 1999, 'Valério', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Foguinho', 2017, 'Tenere 250', 'Boby', 'https://i.ibb.co/JkxfwFz/Foguinho.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, rank, sponsor, image_Uri, status) VALUES ('Gallo', 2008, 'Fat Boy', 'Vice Presidente', 'Mineiro', 'https://i.ibb.co/FYFbgDY/Gallo.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, status) VALUES ('Gunji', 1999, 'Deluxe', 'André', 1);
INSERT INTO tb_member (name, since, sponsor, status) VALUES ('Jane', 2013, 'André', 1);
INSERT INTO tb_member (name, since, sponsor, status) VALUES ('Cícero', 2013, 'André', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Junior', 2009, 'Tornado 250', 'Gallo', 'https://i.ibb.co/D74ZvSD/Junior.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, status) VALUES ('Jovilson', 2020, 'Fat Boy', 'André', 1);
INSERT INTO tb_member (name, since, motorcycle, rank, sponsor, image_Uri, status) VALUES ('Kleber', 2006, 'Drag star', 'Diretor Disciplinar', 'André', 'https://i.ibb.co/YfFqgQZ/Kleber.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, status) VALUES ('Lana', 2010, 'Fat Boy', 'André', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Lelê', 2016, 'Shadow 600', 'Buunito', 'https://i.ibb.co/DVx4W9r/Lele.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Líbia', 2016, 'Shadow 600', 'Buunito', 'https://i.ibb.co/68fD0Dg/Libia.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, status) VALUES ('Marquinho', 2020, 'CG', 'Sérgio', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Mike', 2018, 'Fat Boy', 'Foguinho', 'https://i.ibb.co/84zhYvn/Mike.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Nandinho', 2015, 'CG', 'André', 'https://i.ibb.co/vVS3Yrf/Nandinho.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Paulo Zé do caixão', 2020, 'GS850', 'André', 'https://i.ibb.co/4NNDsC4/Paulo.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, rank, sponsor, image_Uri, status) VALUES ('PATY', 1998, 'Fat Boy', 'Diretor Tesouraria', 'André', 'https://i.ibb.co/rQ2zQpP/Paty.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Pica Pau', 2017, 'XT 660', 'Kleber', 'https://i.ibb.co/gR98Byw/Pica-Pau.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Rafinha', 2019, 'Virago 535', 'André', 'https://i.ibb.co/TB240XS/Rafael.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, rank, sponsor, status) VALUES ('Sérgio', 2018, 'NC650', 'Diretor Adjunto Tesouraria', 'Foguinho', 1);
INSERT INTO tb_member (name, since, rank, sponsor, status) VALUES ('Big Boy', 2010, 'Diretor Regional Santa Catarina', 'DPulgas', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Tiago', 2017, 'Transalp', 'André', 'https://i.ibb.co/znrJdQ0/Tiago.jpg', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, status) VALUES ('XIKRETY', 2020, 'NC650', 'André', 1);
INSERT INTO tb_member (name, since, motorcycle, sponsor, image_Uri, status) VALUES ('Wolmer Gigante', 2020, 'Falcon', 'André', 'https://i.ibb.co/0sBsVmy/Wolmer.jpg', 1);

INSERT INTO tb_event (moment, description, address, status) VALUES (TIMESTAMP WITH TIME ZONE '2021-05-19T10:00:00Z', 'Aniversário Junior', 'R. Manoel Bôsco Ribeiro, 46 - Jardim das Industrias, São José dos Campos', 0);
